export class AppConstant {
  static TOKEN: string = ''
  static USERNAME: string = ''
  static NICKNAME: string = ''
  static PASSWORD: string = ''
  static ID: string = ''
  static readonly USER_ID: string = 'user_id'
  static readonly COOKIE: string = 'cookie'
  static COOKIE_VALUE: string = ''
  static readonly KEY_USERNAME: string = 'username'
  static readonly KEY_PASSWORD: string = 'password'
  static readonly KEY_NICKNAME: string = 'nickname'
  static readonly KEY_USERINFO: string = 'userinfo'
  static readonly IS_LOGIN: string = 'is_login'
  //Emitter Flag
  static readonly FLAG_NO_LOGIN: number = -1001
  static readonly FLAG_LOGIN_SUCCESS: number = 100101
  static readonly FLAG_CREATE_TODO: number = 100102
  static readonly FLAG_UPDATE_TODO: number = 100103
}
