export class HomeApi {
  static readonly API_BANNER: string = 'banner/json'
  static readonly API_HOME_ARTICLE_LIST: string = 'article/list'
  static readonly API_WELCOME_LEARN: string = 'popular/route/json'
  static readonly API_WELCOME_QUESTION: string = 'popular/wenda/json'
  static readonly API_WELCOME_COLUMN: string = 'popular/column/json'
  static readonly API_SEARCH_HOT_WORD: string = 'hotkey/json'
  static readonly API_WEB_SITE: string = 'friend/json'
  static readonly API_HOME_SEARCH: string = 'article/query/'
  static readonly API_UNREAD_MSG_COUNT: string = 'message/lg/count_unread/json'
  static readonly API_MSG_UNREAD_LIST:string='message/lg/unread_list/'
}