export class HomeApi {
  static readonly API_BANNER: string = 'banner/json'
  static readonly API_HOME_ARTICLE_LIST: string = 'article/list'
  static readonly API_WELCOME_LEARN: string = 'popular/route/json'
  static readonly API_WELCOME_QUESTION: string = 'popular/wenda/json'
  static readonly API_WELCOME_COLUMN: string = 'popular/column/json'
  static readonly API_SEARCH_HOT_WORD: string = 'hotkey/json'
  static readonly API_WEB_SITE: string = 'friend/json'
  static readonly API_HOME_SEARCH:string='article/query/'
}